### ISSUE TITLE
Test on ES3 browsers

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.JavaScript#15]

**Comment by niemyjski** [comment]
@ejsmith Everything is now working great in IE9.. Do you think we should rename the `ExceptionlessClient.default` property to `ExceptionlessClient.Default` as `default` is a js keyword and breaks IE8 (There are other things that also break ie8 like property getters/setters and `Object.defineproperty`). All other browsers don't seem to have a problem with this..

**Comment by ejsmith** [comment]
Yeah, I guess that would be the best way to have it still match the .NET client.

**Comment by niemyjski** [comment]
But the config property and namespace don't match.. But a atep closer to ie8

Sent from Outlook




On Tue, Jun 2, 2015 at 12:45 PM -0700, "Eric J. Smith" <notifications@github.com> wrote:












Yeah, I guess that would be the best way to have it still match the .NET client.

**Comment by niemyjski** [comment]
@ejsmith But the config property and namespace don't match.. But a step closer to ie8.

**Comment by Pfinl** [comment]
Is the "default as a keyword" issue actually going to be resolved soon for IE8?  I cannot use this API until it is, as we need to support IE8 and this issue completely breaks my application.  Thanks.

**Comment by niemyjski** [comment]
@pfinl, starting January 12th Microsoft is officially only supporting IE 11 https://support.microsoft.com/en-us/lifecycle?p1=13418

We've thought about doing an ie8 build but due to Microsoft discontinuing support for legacy browsers and the market share of ie8 being almost non existant we decide to focus our resources in other areas.. 

 With this said if you want to do a pull request for an ie8 version.. We'd be more than happy to work with you and and help support it going forward. I think the best thing todo would be to do a string replace on the default keyword and do something special for object defines where we use properties.. I'd like to have a exceptionless.legacy.js file that only contains these changes. Thoughts??

**Comment by Pfinl** [comment]
I hear ya with focusing on supported browsers!  Unfortunately, we still
have to support IE8 for the big enterprises that refuse to upgrade.

I got around IE8 completely breaking things by changing my syntax to
["default"] instead of .default.  Of course, it still doesn't actually work
in IE8 because of the Object.defineProperty limitation as you mentioned.
I'm under a pretty tight deadline to get this project I'm working on done,
but if I find time to come up with a good solution for IE8 - I'll
definitely let you know and I'd be happy to work with you to get that
incorporated into a legacy file.

And by the way - in all other browsers, it's been working great!

Thanks!
