### ISSUE TITLE
Microsoft IE/Edge doesn't seem to be pulling down client configuration settings.

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.JavaScript#23]
I noticed this during testing that it doesn't seem to be parsing the header properly.

**Comment by niemyjski** [comment]
It appears that IE was returning a string `'\nX-Exceptionless-ConfigVersion: 10\r\nX-RateLimit-Limit: 3500\r\nX-RateLimit-Remaining: 3483\r\n\r\n';` that started with a newline character.

**Comment by srijken** [comment]
Also seen in IE11, didn't check older browsers.

The reason here is that `XHR.getAllResponseHeaders()` returns a string that doesn't confirm to the [specification](http://www.w3.org/TR/XMLHttpRequest/#the-getallresponseheaders%28%29-method). The string returned in the error instance:

```
\nX-Exceptionless-ConfigVersion: 10\r\nX-RateLimit-Limit: 3500\r\nX-RateLimit-Remaining: 3483\r\n\r\n
```

The problem that causes the issue in Exceptionless.Javascript is the fact that the result of `getAllResponseHeaders()` starts of with `'\n`. That in turn causes the header to be stored like this:

```
headers['\nX-Exceptionless-ConfigVersion'] = 10;
```

Because the value is read with the extra `\n`, the current configVersion can't be read, and that causes the config API endpoint to never be called.

Fix is to trim the keys when we assign values to the object property.

Although the leading `\n` causes the problem, the trailing `\r\n\r\n` shouldn't be there either according to the specification

**Comment by niemyjski** [comment]
Logged as a bug here: https://connect.microsoft.com/IE/feedbackdetail/view/1929694/ie-edge-incorrectly-return-the-header-with-a-leading-new-line-character
