### ISSUE TITLE
Ability to send in events synchronously 

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.JavaScript#61]
We need to send in events synchronously to ensure unit tests calling process(true) works as well as giving us the ability to submit events on the unload event.

https://github.com/exceptionless/Exceptionless.JavaScript/issues/59

**Comment by leidegre** [comment]
About that, I just noted the following

~~~
exceptionless.js:411 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
~~~

Edit: appears to be related to the `TraceKit.computeStackTrace` function. Not sure what to make of it but it's an annoying warning that I'd like to silence, if possible.

Edit 2: this could be a separate issue...

**Comment by niemyjski** [comment]
Yeah, that is coming from TraceKit, would you mind taking a closer look into this. I think it could be that trace kit builds up requests for processing source files, perhaps this needs to be disabled

**Comment by leidegre** [comment]
I've only seen it once, I'll keep an eye open and if I see it again, I'll open a new issue?

**Comment by niemyjski** [comment]
Yeah, please let us know if you see it again

**Comment by niemyjski** [comment]
This should be resolved as we rewrote all of our http stack in v2 release. If you are still running into this please let us know.
