### ISSUE TITLE
Repeat send options HTTP method

### ISSUE THREAD

**Issue by platstar** [exceptionless/Exceptionless.JavaScript#74]
When I use exceptionless.js on my page, I found a behavior below this

![request](https://user-images.githubusercontent.com/4907156/27573602-3993cdea-5b45-11e7-84c4-f5ceb310d11f.PNG)

it seems to check server health or something every 2 minutes.
so it 's possible to close these requests from client side?

**Comment by niemyjski** [comment]
What you are seeing is part of our real time configuration happing. How this works is we do a request 5 seconds after page load (so we don't slow down your page load) and every 2 minutes if you don't submit any events (otherwise it gets the config version from the submission header). This ensures that the client always has the latest configuration (you can send down your own values and get them from within your application to do anything you want like a/b testing) 

You can disable this completely by calling the following method on client.config. updateSettingsWhenIdleInterval(0);
https://github.com/exceptionless/Exceptionless.JavaScript/blob/master/src/configuration/Configuration.ts#L246

If you have any questions or need any assistance please let me know.
