### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by matthew-churcher** [exceptionless/Exceptionless.JavaScript#78]
Would it be possible to have breadcrumbs? The concept of breadcrumbs is rather than shipping log messages constantly incase some thing happens. Instead logs messages are buffered and the last X are sent along with the error.

**Comment by matthew-churcher** [comment]
Ah the .net SDK has this. Under the name tracing. It can be enabled in the config. Can we do this in JavaScript?

**Comment by niemyjski** [comment]
Yes, you could do this by writing a plugin that attaches a list of breadcrumbs to the events extended data. You could write a plugin that's like our deduper and it just stores the log messages until an error comes through and then it rolls up or submits all of those log messages. Would this work?

Personally, I would like to see tracing go away completely in .net and I'd rewrite it to just submit log messages. We get asked a lot of questions about searching it and how it works. It's confusing as users think it will just be submitted in one batch on a new event automatically instead of being attached to every submitted event.

**Comment by niemyjski** [comment]
I'm going to close this because I feel like the best way to accomplish this is still through a custom plugin. Please upvote or comment if reading this if there is something more you think this project could do around this.
